### ISSUE TITLE
We need a code of conduct

### ISSUE THREAD

**Issue by dhagberg** [WinterTechForum/wtf-code-of-conduct#1]
That.

**Comment by billrobertson42** [comment]
Were there issues? Also, is this WRT the conference or the mailing list or
both?

**Comment by dhagberg** [comment]
Hi Bill —

No issues but M8ttyb said he had some coworkers that were WTF-curious but
wanted to know about a code of conduct (see the Slack #general channel).
Seemed like something we should have since other conferences are doing it.
Documenting the WTF code seems worthwhile.

Any thoughts on your end?

- D. J.
